name: phpcs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup PHP and Dependencies
      uses: ./.github/actions/setup

    - name: Run phpcs
      run: 'vendor/bin/phpcs -q --no-colors --report=checkstyle | cs2pr'
