name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - '8.4'
          - '8.5'

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup PHP and Dependencies
      uses: ./.github/actions/setup
      with:
        php-version: ${{ matrix.php-version }}

    - name: Run test suite
      run: vendor/bin/phpunit
